### Test script for developing niter2 python port

In [ ]:
# Imports
import finalproject as proj

In [ ]:
proj.show_epilines("test", "SIFT")

In [ ]:
proj.show_epilines("test", "ORB")

In [1]:
import finalproject as proj
import numpy as np
np.set_printoptions(suppress=True)

proj.test_pipeline("test", "SIFT", False)

running warmup....
n: [5. 5.], n_prime: [3. 3.]
warmup complete
[[  9. 225.]
 [  9. 216.]
 [ 14. 296.]
 [ 17. 261.]
 [ 18. 127.]]

[[  5. 223.]
 [  6. 214.]
 [ 11. 295.]
 [ 12. 260.]
 [ 15. 124.]]

[[    1.07326294  1255.98782151  -142.90615119]
 [-1261.60934979     3.34508106    23.34243086]
 [  141.51516519   -24.46183154     0.12185632]]

n: [279947.74435929  -5538.75124228], n_prime: [-283710.92917205   12032.07179997]
n: [268644.92722867  -6830.46632159], n_prime: [-272356.4450239    12001.96607045]
n: [370385.30708532 -12867.5615049 ], n_prime: [-373279.82669274   18549.51166258]
n: [326426.80659556 -14246.24869171], n_prime: [-329120.27966114   22200.39729008]
n: [155615.68265957 -18486.00776492], n_prime: [-160063.5535258    23008.14424988]


In [1]:
import finalproject as proj
import numpy as np

lp = np.array([[9,225],[9,216],[14,296],[17,261],[18,127]], dtype=np.float32)
rp = np.array([[5,223],[6,214],[11,295],[12,260],[15,124]], dtype=np.float32)
sp = np.array([[1,0,0], [0,1,0]], dtype=np.float32)
ep = np.array([[1.07326294, 1255.98782151, -142.90615119],
               [-1261.60934979, 3.34508106, 23.34243086],
               [141.51516519,-24.46183154,0.12185632]], dtype=np.float32)
algo = np.array([[1]], dtype=float)

print(lp.shape)

arr_add = np.ones(lp.shape[0], dtype=np.float32).reshape(-1,1)
print(arr_add.shape)

print(ep)
proj._non_iter_vectorized(algo, lp, rp, ep, sp)

(5, 2)
(5, 1)
[[ 1.0732629e+00  1.2559878e+03 -1.4290616e+02]
 [-1.2616094e+03  3.3450811e+00  2.3342430e+01]
 [ 1.4151517e+02 -2.4461832e+01  1.2185632e-01]]
n_mat shape: (5, 2), n_mat_prime shape: (5, 2)
[[279947.75    -5538.7515]
 [268644.9     -6830.467 ]
 [370385.3    -12867.562 ]
 [326426.8    -14246.249 ]
 [155615.67   -18486.008 ]]

[[-283710.94    12032.072]
 [-272356.47    12001.966]
 [-373279.84    18549.512]
 [-329120.3     22200.398]
 [-160063.56    23008.146]]
