### Test script for developing niter2 python port

In [ ]:
# Imports
import finalproject as proj

In [ ]:
proj.show_epilines("test", "SIFT")

In [ ]:
proj.show_epilines("test", "ORB")

In [1]:
import finalproject as proj
import numpy as np
np.set_printoptions(suppress=True)

proj.test_pipeline("test", "SIFT", False)

running warmup....
a: 60.0, b: 34.0, c: 15.0, d: 16.0, lambda: 0.3, del_x: [1.5 1.5], del_x': [0.9 0.9]
warmup complete
[[  9. 225.]
 [  9. 216.]
 [ 14. 296.]
 [ 17. 261.]
 [ 18. 127.]]

[[  5. 223.]
 [  6. 214.]
 [ 11. 295.]
 [ 12. 260.]
 [ 15. 124.]]

[[    1.07326294  1255.98782151  -142.90615119]
 [-1261.60934979     3.34508106    23.34243086]
 [  141.51516519   -24.46183154     0.12185632]]

a: 2162643966314.2026, b: 79519039710.32135, c: 1268563.378970143, d: 79501787561.75389, lambda: 7.977341086269824e-06, del_x: [ 2.23323864 -0.04418451], del_x': [-2.26325885  0.09598394]
a: 1623839588189.436, b: 73269416265.74086, c: 938038.0004927353, d: 73259020855.3321, lambda: 6.401747121056486e-06, del_x: [ 1.71979689 -0.04372692], del_x': [-1.74355709  0.07683355]
a: 2420273960717.0254, b: 138516381621.22803, c: 1370936.642114103, d: 138504404028.10654, lambda: 4.948858400284434e-06, del_x: [ 1.83298444 -0.06367974], del_x': [-1.84730901  0.09179891]
a: 3070191227609.668, b: 10778521589

In [1]:
import finalproject as proj
import numpy as np

lp = np.array([[9,225],[9,216],[14,296],[17,261],[18,127]], dtype=np.float32)
rp = np.array([[5,223],[6,214],[11,295],[12,260],[15,124]], dtype=np.float32)
sp = np.array([[1,0,0], [0,1,0]], dtype=np.float32)
ep = np.array([[1.07326294, 1255.98782151, -142.90615119],
               [-1261.60934979, 3.34508106, 23.34243086],
               [141.51516519,-24.46183154,0.12185632]], dtype=np.float32)
algo = np.array([[1]], dtype=float)
arr_add = np.ones(lp.shape[0], dtype=np.float32).reshape(-1,1)

proj._non_iter_vectorized(algo, lp, rp, ep, sp)

(5, 2)
(5, 1)
[[ 1.0732629e+00  1.2559878e+03 -1.4290616e+02]
 [-1.2616094e+03  3.3450811e+00  2.3342430e+01]
 [ 1.4151517e+02 -2.4461832e+01  1.2185632e-01]]
lambda_mat shape: (5, 5), del_x: (5, 2)
[[-0.7180806   0.47941983]
 [ 0.20375702  0.44156465]
 [ 3.318598    0.31204188]
 [13.179909   -0.09498492]
 [55.77088    -1.8522338 ]]
